### PR TITLE
French translation of the FAQ

### PR DESCRIPTION
**Pull request by chetta19**
French translation of the FAQ page.

### CODE REVIEW

**Comment by jmandel** [comment]
Thanks for this! I've merged into the staging site at https://onboarding-staging.smarthealth.cards/faq.html (https://github.com/smart-health-cards/smart-health-cards-staging.github.io)

**Comment by jmandel** [comment]
Will note that the Menu on the /fr/faq.html page isn't expanding on mobile in current state, so you get "stuck" in navigation.

**Comment by chetta19** [comment]
Hi Josh,

I'm not sure what issue Will noted. Do you have more details.
I tried all the menu and I have not found any that do not work.
https://www.loom.com/share/31e6711c85d246be9819ab785f448be2

David.

**Comment by jmandel** [comment]
Fixed in https://github.com/smart-health-cards/smart-health-cards-staging.github.io/commit/69040b98a344ae9c3b9e5dc9fc4792297292fd9e

**Pull request merged**
