### PR TITLE
Site Refresh: Find My Issuer Feature

### PR DESCRIPTION
**Pull request by KreigD**
Implements the "Find My Issuer" user flow, along with a number of site refreshes. The following has been reviewed and approved by the v-team:

- Updates to homepage (reviewed and approved as text changes and then again on staging)
- Updates to FAQ (reviewed and approved as text changes and then again on staging)
- Creation of “how they work” page (per v-team request, reviewed and approved as text changes and then again on staging)
- Creation of bot and issuer support page per spec/plan (reviewed and approved as text changes and then again on staging)
- Updates to nav and footer per plan

### CODE REVIEW

**Comment by jmandel** [comment]
Beet cool! For locations, was there a single source file from which all of the markdown files were generated? It would be good to check this in and any automation scripts that were used to generate the individual markdowns files in case we need to tweak anything about that process in the future.

Also can you clarify it with this file structure where the locations are all in a folder called `_locations` -- What will be the static URL for, say, the English language `california.html` page?

This PR adds several relative links that I think could be absolutely links, per the changes from Max Masnick last week. E.g.,

    <link href="../css/main.css"

**Comment by KreigD** [comment]
> Beet cool! For locations, was there a single source file from which all of the markdown files were generated? It would be good to check this in and any automation scripts that were used to generate the individual markdowns files in case we need to tweak anything about that process in the future.
> 
> Also can you clarify it with this file structure where the locations are all in a folder called `_locations` -- What will be the static URL for, say, the English language `california.html` page?
> 
> This PR adds several relative links that I think could be absolutely links, per the changes from Max Masnick last week. E.g.,
> 
> ```
> <link href="../css/main.css"
> ```

The `_location` markdown files were added manually.

The `_config.yml` file has the structure for the location page URLs: `permalink: /en/:name.html`. So `california.md` would be `/en/california.html` and `cayman_islands.md` would be `/en/cayman-islands.html`. Is there a different URL structure preferred or required?

I will review those absolute link changes and incorporate them into these.

**Comment by jmandel** [comment]
Thanks! Also in footer is there a reason why some links explicitly point to English and others don't?

**Comment by KreigD** [comment]
> Thanks! Also in footer is there a reason why some links explicitly point to English and others don't?

It's because of the translated FAQ pages. Without the `/en/` there, you can't get from a translated FAQ page to any other subpages on the site.

**Comment by KreigD** [comment]
> This PR adds several relative links that I think could be absolutely links, per the changes from Max Masnick last week. E.g.,
> 
> ```
> <link href="../css/main.css"
> ```

Just to clarify, are you referring to the links inside `<head` on this page?

https://github.com/smart-health-cards/smart-health-cards.github.io/blob/f4aba4e79ce8cc390bdb3e6be16a11978d1ca20b/_layouts/page.html

**Comment by jmandel** [comment]
>Just to clarify, are you referring to the links inside <head on this page?

Yes and more broadly all 11 instances of `../` in the PR

**Comment by KreigD** [comment]
Got it, thanks! I also just noticed the new pathing for `/en/index.html`.

**Review by KreigD — COMMENTED** [review]
@jmandel The changes we discussed have been made

- Relative links made absolute
- Bringing the  `/en/index.html` flow into line with production

**Pull request merged**
